{
 "title": "New dashboard",
 "time": { "from": "2020-11-08T21:37:35.052Z", "to": "2020-11-09T09:37:35.052Z" },
 "panels": [
  { "title": "Current Latency Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Segment Read Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "query": "from(bucket: \"monitoring_last\")\r\n|> filter(fn: (r) => r._measurement == \"pravega_segmentstore_segment_read_latency_ms_percentile\"\r and r.phi == \"0.99\" and r.host =~ /^${host:pipe}$/ )\r\n|> range($range)\r\n|> group()\n|> last()\n"
    }
   ]
  },
  {
   "title": "Segment Write Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "query": "from(bucket: \"monitoring_last\")\r\n|> filter(fn: (r) => r._measurement == \"pravega_segmentstore_segment_write_latency_ms_percentile\"\r and r.phi == \"0.99\" and r.host =~ /^${host:pipe}$/ )\r\n|> range($range)\r\n|> group()\n|> last()\n"
    }
   ]
  },
  {
   "title": "Storage Write Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "query": "from(bucket: \"monitoring_last\")\r\n|> filter(fn: (r) => r._measurement == \"pravega_segmentstore_storage_write_latency_ms_percentile\"\r and r.phi == \"0.99\" and r.host =~ /^${host:pipe}$/ )\r\n|> range($range)\r\n|> group()\n|> last()\n"
    }
   ]
  },
  {
   "title": "Storage Read Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "query": "from(bucket: \"monitoring_last\")\r\n|> filter(fn: (r) => r._measurement == \"pravega_segmentstore_storage_read_latency_ms_percentile\"\r and r.phi == \"0.99\" and r.host =~ /^${host:pipe}$/ )\r\n|> range($range)\r\n|> group()\n|> last()\n"
    }
   ]
  },
  {
   "title": "Segment Write Bytes/Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_last\")\n|> filter(fn: (r) => r._measurement == \"pravega_segmentstore_stream_write_bytes\"  and r.host =~ /$host/)\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"host\", \"_measurement\"])\n|> window(every: 1m)\n|> mean()\n|> rename(columns: {_stop: \"_time\"})\n|> group()\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Segment Read Bytes/Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_last\")\n|> filter(fn: (r) => r._measurement == \"pravega_segmentstore_stream_read_bytes\"  and r.host =~ /$host/)\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"host\", \"_measurement\"])\n|> window(every: 1m)\n|> mean()\n|> rename(columns: {_stop: \"_time\"})\n|> group()\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Storage Write Bytes/Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_last\")\n|> filter(fn: (r) => r._measurement == \"pravega_segmentstore_storage_write_bytes\"  and r.host =~ /$host/)\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"host\", \"_measurement\"])\n|> window(every: 1m)\n|> mean()\n|> rename(columns: {_stop: \"_time\"})\n|> group()\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Storage Read Bytes/Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_last\")\n|> filter(fn: (r) => r._measurement == \"pravega_segmentstore_storage_read_bytes\"  and r.host =~ /$host/)\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"host\", \"_measurement\"])\n|> window(every: 1m)\n|> mean()\n|> rename(columns: {_stop: \"_time\"})\n|> group()\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "BK Write Exclusive Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_last\")\n|> filter(fn: (r) => r._measurement == \"pravega_segmentstore_bookkeeper_write_latency_ms_percetile\"  and r.host =~ /$host/)\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"host\", \"_measurement\"])\n|> window(every: 1m)\n|> mean()\n|> rename(columns: {_stop: \"_time\"})\n|> group()\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Container Operation Processor Delay Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_last\")\n|> filter(fn: (r) => r._measurement == \"pravega_segmentstore_container_operation_processor_delay_ms\"  and r.host =~ /$host/)\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"host\", \"_measurement\"])\n|> window(every: 1m)\n|> mean()\n|> rename(columns: {_stop: \"_time\"})\n|> group()\n\n\n\n\n\n"
    }
   ]
  }
 ]
}